---

- name: docker-machine proxmox vm template
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Create an lxc
      include_tasks: tasks/create-lxc.yaml
