---

- name: docker-machine proxmox vm template
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  vars_files:
    - vars/main.yml
  tasks:
    - name: Clean all templates
      include_tasks: tasks/t00-clean.yaml
